# Etapa 1: Build da aplicação
FROM mcr.microsoft.com/dotnet/sdk:9.0.100-rc.2.24474.11 AS build
WORKDIR /app

# Copia os arquivos do projeto e restaura as dependências
COPY *.csproj .
RUN dotnet restore

# Copia o restante dos arquivos e compila a aplicação
COPY . .
RUN dotnet publish -c Release -o /out --no-restore

# Etapa 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0.0-rc.2 AS runtime
WORKDIR /app

# Copia a aplicação compilada
COPY --from=build /out .

# Define o ponto de entrada
ENTRYPOINT ["dotnet", "BudgetControl.dll"]
