services:
  - name: budgetcontrol-api
    type: web
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: true
      - key: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
        value: true
